package caravan.world;

/**
 * Types of merchandise.
 */
public enum Merchandise {
	RAW_WOOL,
	UNSPUN_COTTON,
	FLAX,
	ANIMAL_SKINS,
	LINEN,
	COTTON,
	SILK,
	WOOL,
	CLOTHING_CHEAP,
	CLOTHING_REGULAR,
	CLOTHING_LUXURY,
	MEAT_RED_FRESH,
	MEAT_RED_SALTED,
	MEAT_RED_SMOKED,
	MEAT_POULTRY_FRESH,
	MEAT_POULTRY_SALTED,
	MEAT_POULTRY_SMOKED,
	MEAT_FISH_FRESH,
	MEAT_FISH_SALTED,
	MEAT_FISH_SMOKED,
	MEAT_SAUSAGE,
	MEAT_PATE,
	GRAIN,
	BREAD,
	EGGS,
	DAIRY_MILK,
	DAIRY_CHEESE,
	HONEY,
	SUGAR,
	FOOD_OIL_FAT,
	BEER,
	WINE,
	LIQUOR,
	MEAD,
	WATER_FRESH,
	FRUIT_FRESH,
	FRUIT_DRIED,
	FRUIT_JAM,
	VEGETABLES_FRESH,
	VEGETABLES_PICKLED,
	SPICES,
	SALT,
	BOOK,
	GOLD_ORE,
	GOLD_INGOT,
	SILVER_ORE,
	SILVER_INGOT,
	IRON_ORE,
	IRON_INGOT,
	COPPER_ORE,
	COPPER_INGOT,
	TIN_ORE,
	TIN_INGOT,
	LEAD_ORE,
	LEAD_INGOT,
	COAL,
	JEWELS,
	JEWELRY,
	ARMOR_AND_WEAPONS,
	TOOLS,
	WOOD_LOG,
	WOOD_FUEL,
	WOOD_TIMBER,
	STONE,
	LIMESTONE,
	PERFUME
	;

	public static final Merchandise[] VALUES = values();

	/** Merchandise categories and subcategories. */
	public enum Category {
		TEXTILE(RAW_WOOL, UNSPUN_COTTON, FLAX, ANIMAL_SKINS, LINEN, COTTON, SILK, WOOL),
		TEXTILE_RAW(RAW_WOOL, UNSPUN_COTTON, FLAX, ANIMAL_SKINS),
		TEXTILE_CHEAP(LINEN, COTTON),
		TEXTILE_LUXURY(SILK, WOOL),
		CLOTHING(CLOTHING_CHEAP, CLOTHING_REGULAR, CLOTHING_LUXURY),
		FOOD(MEAT_RED_FRESH, MEAT_RED_SALTED, MEAT_RED_SMOKED, MEAT_POULTRY_FRESH, MEAT_POULTRY_SALTED, MEAT_POULTRY_SMOKED, MEAT_FISH_FRESH, MEAT_FISH_SALTED, MEAT_FISH_SMOKED,
				MEAT_SAUSAGE, MEAT_PATE, GRAIN, BREAD, EGGS, DAIRY_MILK, DAIRY_CHEESE, HONEY, SUGAR, FOOD_OIL_FAT, BEER, WINE, LIQUOR, MEAD, WATER_FRESH, FRUIT_FRESH, FRUIT_DRIED,
				FRUIT_JAM, VEGETABLES_FRESH, VEGETABLES_PICKLED, SPICES, SALT),
		FOOD_MEAT(MEAT_RED_FRESH, MEAT_RED_SALTED, MEAT_RED_SMOKED, MEAT_POULTRY_FRESH, MEAT_POULTRY_SALTED, MEAT_POULTRY_SMOKED, MEAT_FISH_FRESH, MEAT_FISH_SALTED, MEAT_FISH_SMOKED, MEAT_SAUSAGE, MEAT_PATE),
		FOOD_MEAT_RED(MEAT_RED_FRESH, MEAT_RED_SALTED, MEAT_RED_SMOKED),
		FOOD_MEAT_POULTRY(MEAT_POULTRY_FRESH, MEAT_POULTRY_SALTED, MEAT_POULTRY_SMOKED),
		FOOD_MEAT_FISH(MEAT_FISH_FRESH, MEAT_FISH_SALTED, MEAT_FISH_SMOKED),
		FOOD_ALCOHOLIC_DRINK(BEER, WINE, LIQUOR, MEAD),
		FOOD_FRUIT(FRUIT_FRESH, FRUIT_DRIED, FRUIT_JAM),
		FOOD_VEGETABLE(VEGETABLES_FRESH, VEGETABLES_PICKLED),
		MINING(GOLD_ORE, GOLD_INGOT, SILVER_ORE, SILVER_INGOT, IRON_ORE, IRON_INGOT, COPPER_ORE, COPPER_INGOT, TIN_ORE, TIN_INGOT, LEAD_ORE, LEAD_INGOT, COAL, JEWELS),
		MINING_METAL_PRECIOUS(GOLD_ORE, GOLD_INGOT, SILVER_ORE, SILVER_INGOT),
		MINING_METAL_COMMON(IRON_ORE, IRON_INGOT, COPPER_ORE, COPPER_INGOT, TIN_ORE, TIN_INGOT, LEAD_ORE, LEAD_INGOT),
		WOOD(WOOD_LOG, WOOD_FUEL, WOOD_TIMBER),
		STONE(Merchandise.STONE, LIMESTONE),
		OTHER(ARMOR_AND_WEAPONS, TOOLS),
		OTHER_LUXURY(BOOK, JEWELRY, PERFUME)
		;

		public final Merchandise[] merch;

		Category(Merchandise...merch) {
			this.merch = merch;
		}

		public static final Category[] VALUES = values();
	}
}
